### PR TITLE
Update readme.txt

### PR DESCRIPTION
**Pull request by hvz2015**
local port usage must be like this /l PortNum

### Contributor License Agreement (CLA)
* The Pull Request feature will be considered by STMicroelectronics after the signature of a **Contributor License Agreement (CLA)** by the submitter.
* If you did not sign such agreement, please follow the steps mentioned in the [CONTRIBUTING.md](https://github.com/STMicroelectronics/STM32CubeF4/blob/master/CONTRIBUTING.md) file.

### CODE REVIEW

**Comment by hvz2015** [comment]
echotool example change

**Comment by RKOUSTM** [comment]
Hi @hvz2015,

Thank you for your report. An internal tracker has been logged and a fix will be implemented and made available in the frame of a future release.

Thank you once again for your report.

With regards,

**Comment by RKOUSTM** [comment]
ST Internal Reference: 117528.

**Comment by RKOUSTM** [comment]
Hi @hvz2015,

Thank you for your contribution.  This issue has been fixed in the frame of version v1.27.0 of the STM32CubeF4 published recently. Please allow me then to close this thread.

Thank you again for your report.

With regards,

**Comment by RKOUSTM** [comment]
Hi @hvz2015,

Thank you for your contribution. This issue has been fixed in the frame of version v1.27.0 of the STM32CubeF4 published recently. Please allow me then to close this thread.

Thank you again for your contribution.

With regards,

**Pull request closed without merging**
