### PR TITLE
Whitespace and character set housekeeping

### PR DESCRIPTION
**Pull request by tcv-git**
This pull-request makes no functional changes.  It only:

1.  Strips trailing white space from the end of lines in driver source files.

2. Converts the character set of driver source files to ASCII.  Some were previously Windows-1252, and some were UTF-8.  Note that this only affects special characters (curly quotes etc) in comments, not code.

3.  Expands tabs to spaces in driver source files.  In different files tabs are expanded to 2, 4 or 8 spaces.  Most indentation was already in spaces.  This makes it possible to determine the correct number of spaces that the original author intended and to make the files look consistent whatever the editor setting.

### CODE REVIEW

**Comment by tcv-git** [comment]
Hi Ali, Frederic,

I have already done this job for many of the other cube packages, and am happy to do it for all of them if it is welcome and you want to merge it.  I have scripts set up for this so it isn't a big task for me.

Thanks,
Tom

**Comment by ALABSTM** [comment]
Hi @tcv-git,

Thank you very much for this contribution. Thank you also for the interest you are showing to our firmware.

For your information, the majority of the source files in the firmware package are generated from other "upstream" ones. These are the ones that we shall cleanup internally.
Otherwise, after we merge this pull request of yours, there is a risk many of the changes you made are overwritten by the next firmware package release.

However, your contribution has been an opportunity to tackle the subject with our software quality team. We are currently discussing to find a way to systematically integrate such a good practice to our future publications.

In the meanwhile, may I ask you to share your scripts with us if you don't mind?

Thank you again for your contribution @tcv-git. I will keep you informed as soon as I have something new regarding this subject.

With regards,

**Comment by josesimoes** [comment]
@ALABSTM allow me to step in.

I'm with the core team of the [.NET nanoFramework](https://github.com/nanoframework) project. We've recently added an automated code style check on our PRs for the firmware images.
We are using [clang formatter](http://clang.llvm.org/docs/ClangFormat.html) for that.

It's basically a matter of deciding on a code style and add the configuration rules on [a file](https://github.com/nanoframework/nf-interpreter/blob/develop/.clang-format). On a PR a [script](https://github.com/nanoframework/nf-interpreter/blob/develop/azure-pipelines-templates/check-code-style.yml) is run to check for violations and generates a commit with the fixes that can be reviewed and merged.

Locally, developers can install lvvm tools and run the formatter on the IDE they are using. (ideally this would be done before committing code).

**Comment by tcv-git** [comment]
Hi Ali,

The four commands that I use are:
```bash
tr -d '\r'
```

```bash
sed 's/\s\+$//'
```

```bash
iconv -f UTF-8        -t US-ASCII//TRANSLIT
iconv -f WINDOWS-1252 -t US-ASCII//TRANSLIT
```

```bash
expand -t2
expand -t4
expand -t8
```

These all run from standard-in to standard-out.

The part that almost certainly will be done wrong by an automated tool such the other poster is suggesting is determining the tab width to use.  I half wrote a program to do it but didn't finish it, so I will post an attachment containing the files that I have manually examined to determine the correct settings.  It also contains a list of which files need converting from UTF-8 and which from 1252. 

The only thing you might want to change is that I always convert CRLF newlines to LF.  This should really be handled automatically by ```.gitattributes``` though so you might want to set that up and not use the ```tr``` command.

**Comment by tcv-git** [comment]
[scripts.tar.gz](https://github.com/STMicroelectronics/STM32CubeF4/files/5308156/scripts.tar.gz)

**Comment by ALABSTM** [comment]
Hi @tcv-git, @josesimoes,

Thank you for your proposals. They have been forwarded to our quality team. The subject is still being discussed. I will let you informed.

With regards,

**Comment by ALABSTM** [comment]
ST Internal Reference: 151833

**Comment by ALABSTM** [comment]
Hi @tcv-git,

Thank you again for this contribution and your proposals. This kind of cleanup will be deployed slowly but surely hopefully.

There is no short-term plan to have it deployed for the moment. Hence, allow me to close this pull-request. The topic will be tracked via our internal trackers. Thank you for your comprehension.

With regards,

**Pull request closed without merging**
